name: 'GitHub Linear Action'
description: 'Pushes issue to linear.app through GH Actions'
inputs:
  linear-key:
    description: 'Linear API Key'
    required: true
  linear-team-id:
    description: 'The ID of the Linear team in which to create the issue in'
    required: true
  title:
    description: 'The title of the issue, can be used as {{ github.event.issue.title }}'
    required: true
  body:
    description: 'The body of the issue, can be used as {{ github.event.issue.body }}'
    required: true
  url:
    description: 'The issue url, can be used as {{ github.event.issue.url` }}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'arrow-up-circle'
  color: 'purple'
